#ifndef SRC_DISPLAY_OLED_FONTS_FREESANSBOLD9PT7B_H_
#define SRC_DISPLAY_OLED_FONTS_FREESANSBOLD9PT7B_H_

#include "Display/SSD1322_GFX.h"

extern const GFXfont FreeSansBold9pt7b;

#endif /* SRC_DISPLAY_OLED_FONTS_FREESANSBOLD9PT7B_H_ */
