#ifndef SRC_DISPLAY_OLED_FONTS_FREESERIFBOLDITALIC24PT7B_H_
#define SRC_DISPLAY_OLED_FONTS_FREESERIFBOLDITALIC24PT7B_H_

#include "Display/SSD1322_GFX.h"

extern const GFXfont FreeSerifBoldItalic24pt7b;

#endif /* SRC_DISPLAY_OLED_FONTS_FREESERIFBOLDITALIC24PT7B_H_ */
