    const char *html_page =
        "<!DOCTYPE html>"
        "<html lang=\"en\">"
        "<head>"
        "  <meta charset=\"UTF-8\">"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
        "  <title>Amplituner</title>"
        "  <style>"
        "    body {"
        "      font-family: Arial, sans-serif;"
        "      text-align: center;"
        "      margin-top: 50px;"
        "    }"
        "    #powerButton {"
        "      width: 150px;"
        "      height: 60px;"
        "      font-size: 20px;"
        "      border: none;"
        "      border-radius: 10px;"
        "      cursor: pointer;"
        "      position: relative;"
        "    }"
        "    .off {"
        "      background-color: red;"
        "      color: white;"
        "    }"
        "    .on {"
        "      background-color: green;"
        "      color: white;"
        "    }"
        "  </style>"
        "<script>"        
            "function fetchState() {"
                "fetch('/state')"
                 ".then(response => response.json())"
                    ".then(data => {"
                        "const button = document.getElementById('powerButton');"
                    "if (data.power === 'ON') {"
                        "button.classList.remove('off');"
                        "button.classList.add('on');"
                        "button.innerText = 'ON';"
                    "} else {"
                        "button.classList.remove('on');"
                        "button.classList.add('off');"
                        "button.innerText = 'OFF';"
                    "}"
                "})"
            ".catch(err => console.error('Error fetching state:', err));"
    "}"
""
    "function togglePower() {"
        "const button = document.getElementById('powerButton');"
        "const currentState = button.classList.contains('on') ? 'OFF' : 'ON';"
        "fetch('/power', {"
        "    method: 'POST',"
         "   headers: { 'Content-Type': 'application/json' },"
          "  body: JSON.stringify({ power: currentState })"
        }).then(() => fetchState());
    }

    // Regularne odpytywanie ESP o stan
    setInterval(fetchState, 2000);
</script>
        "  </script>"
        "</head>"
        "<body>"
        "  <h1>Amplituner</h1>"
        "  <button id=\"powerButton\" class=\"off\" onclick=\"togglePower()\">OFF</button>"
        "</body>"
        "</html>";